#!/bin/bash
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color
if [ $# -eq 0 ]; then
    program_name=$(ls -1t | grep -E '\.(asm|s)$' | head -n 1)
    # extension=$(sed -r 's/(\.[^.]+$){1}//')

    echo PROGRAM_NAME=$program_name > .env
    echo -e "Going to compile the latest file: ${GREEN}" $program_name

    docker compose up
else
    if [ $# -gt 1 ]; then
        echo "Pass only one argument."
        exit 1
    else
        program_name=$1

        echo -e "Going to compile the latest file: ${GREEN}" $program_name
        # program_name=$(echo $program_name | sed -r 's/(\.[^.]+$){1}//')   # Removes file extension

        echo PROGRAM_NAME=$program_name > .env

        docker compose up
        
        pid=$!
        wait $pid

        logs=$(docker compose logs 2>&1)
        if echo "$logs" | head -n 2 | grep -q "assembly_environment  | gcc: fatal error: no input files"; then
            echo -e "${RED}You did not pass the correct file to compile."
            exit 1
        fi
    fi
fi